using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Bücherei.Lib.Migrations.Relational
{
    /// <inheritdoc />
    public partial class InitialRelational : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "autoren",
                columns: table => new
                {
                    AutorId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Firstname = table.Column<string>(type: "text", nullable: false),
                    Surname = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_autoren", x => x.AutorId);
                });

            migrationBuilder.CreateTable(
                name: "buechereien",
                columns: table => new
                {
                    BuechereiId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_buechereien", x => x.BuechereiId);
                });

            migrationBuilder.CreateTable(
                name: "buecher",
                columns: table => new
                {
                    BuchId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Titel = table.Column<string>(type: "text", nullable: false),
                    AutorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_buecher", x => x.BuchId);
                    table.ForeignKey(
                        name: "FK_buecher_autoren_AutorId",
                        column: x => x.AutorId,
                        principalTable: "autoren",
                        principalColumn: "AutorId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AutorBuecherei",
                columns: table => new
                {
                    AutorId = table.Column<int>(type: "integer", nullable: false),
                    BuechereiId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AutorBuecherei", x => new { x.AutorId, x.BuechereiId });
                    table.ForeignKey(
                        name: "FK_AutorBuecherei_autoren_AutorId",
                        column: x => x.AutorId,
                        principalTable: "autoren",
                        principalColumn: "AutorId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AutorBuecherei_buechereien_BuechereiId",
                        column: x => x.BuechereiId,
                        principalTable: "buechereien",
                        principalColumn: "BuechereiId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "autoren",
                columns: new[] { "AutorId", "Firstname", "Surname" },
                values: new object[,]
                {
                    { 1, "Glover", "Debora" },
                    { 2, "Shaw", "Collins" },
                    { 3, "Warren", "Norman" },
                    { 4, "Alyson", "Rogers" },
                    { 5, "Hartman", "Moon" },
                    { 6, "Jean", "Zamora" },
                    { 7, "Solis", "Chambers" },
                    { 8, "Rae", "Espinoza" },
                    { 9, "Doris", "Concepcion" },
                    { 10, "Althea", "William" },
                    { 11, "Ford", "Haynes" },
                    { 12, "Coleman", "Lee" },
                    { 13, "Mattie", "Matilda" },
                    { 14, "Manning", "Holman" },
                    { 15, "Serrano", "Estela" },
                    { 16, "Hudson", "Keri" },
                    { 17, "Branch", "Ramsey" },
                    { 18, "Meyer", "Cote" },
                    { 19, "Hardy", "Lorna" },
                    { 20, "Brooks", "Mathews" },
                    { 21, "Goldie", "Young" },
                    { 22, "Aileen", "Adkins" },
                    { 23, "Madeline", "Wynn" },
                    { 24, "Muriel", "Leticia" },
                    { 25, "Cook", "Amelia" },
                    { 26, "Ramirez", "Hinton" },
                    { 27, "Simpson", "Holloway" },
                    { 28, "Deborah", "Sue" },
                    { 29, "Nadia", "Shana" },
                    { 30, "Mara", "Nichols" },
                    { 31, "Lourdes", "Mariana" },
                    { 32, "May", "Audrey" },
                    { 33, "Lakisha", "Lucy" },
                    { 34, "Helga", "Joann" },
                    { 35, "Karen", "Hughes" },
                    { 36, "Nielsen", "Navarro" },
                    { 37, "Ernestine", "Clarice" },
                    { 38, "Eugenia", "Cotton" },
                    { 39, "Joni", "Lynnette" },
                    { 40, "Betsy", "Neal" },
                    { 41, "Blanche", "Nicole" },
                    { 42, "Carrillo", "Tasha" },
                    { 43, "Thomas", "Francesca" },
                    { 44, "Kelley", "Clay" },
                    { 45, "Johanna", "Katrina" },
                    { 46, "Irma", "Aida" },
                    { 47, "Prince", "Michele" },
                    { 48, "Sherry", "Luella" },
                    { 49, "Dominguez", "Yates" },
                    { 50, "Sears", "Fannie" },
                    { 51, "Jane", "Brigitte" },
                    { 52, "Baxter", "Gillespie" },
                    { 53, "Carol", "Mcclain" },
                    { 54, "Cherie", "Duke" },
                    { 55, "Millicent", "Cortez" },
                    { 56, "Edna", "Davidson" },
                    { 57, "Wallace", "Allen" },
                    { 58, "Harding", "Josefina" },
                    { 59, "Wilson", "Augusta" },
                    { 60, "Miriam", "Alexandra" },
                    { 61, "Hillary", "Lisa" },
                    { 62, "Eula", "Singleton" },
                    { 63, "Lila", "Stafford" },
                    { 64, "Atkinson", "Bettie" },
                    { 65, "Schroeder", "Calhoun" },
                    { 66, "Salas", "Horne" },
                    { 67, "Shanna", "Mccoy" },
                    { 68, "Wilder", "Roy" },
                    { 69, "Dodson", "Marjorie" },
                    { 70, "Ines", "Aguilar" },
                    { 71, "Elinor", "Merle" },
                    { 72, "Marianne", "Liliana" },
                    { 73, "Cathleen", "Alvarado" },
                    { 74, "Perez", "Curry" },
                    { 75, "Dianne", "Flores" },
                    { 76, "Gonzalez", "Lavonne" },
                    { 77, "Ava", "Amalia" },
                    { 78, "Whitaker", "Cox" },
                    { 79, "Cassie", "Osborne" },
                    { 80, "Shirley", "Alston" },
                    { 81, "Wagner", "Mclaughlin" },
                    { 82, "Billie", "Dolores" },
                    { 83, "Obrien", "Malone" },
                    { 84, "Bryan", "Chaney" },
                    { 85, "Boone", "Sampson" },
                    { 86, "Francis", "Dolly" },
                    { 87, "Sheri", "Hyde" },
                    { 88, "Fletcher", "Della" },
                    { 89, "Duncan", "Louella" },
                    { 90, "Raquel", "Everett" },
                    { 91, "Adrienne", "Pennington" },
                    { 92, "Barron", "Clayton" },
                    { 93, "Townsend", "Raymond" },
                    { 94, "Hays", "Perry" },
                    { 95, "Bray", "Griffin" },
                    { 96, "Blair", "Latonya" },
                    { 97, "Michelle", "Caldwell" },
                    { 98, "Blankenship", "Kaitlin" },
                    { 99, "Francis", "Geneva" },
                    { 100, "Cantu", "Olivia" }
                });

            migrationBuilder.InsertData(
                table: "buechereien",
                columns: new[] { "BuechereiId", "Name" },
                values: new object[,]
                {
                    { 1, "Gould deserunt" },
                    { 2, "Dominique amet" },
                    { 3, "Dorsey consectetur" },
                    { 4, "Barker nostrud" },
                    { 5, "Mcmahon nisi" }
                });

            migrationBuilder.InsertData(
                table: "AutorBuecherei",
                columns: new[] { "AutorId", "BuechereiId" },
                values: new object[,]
                {
                    { 1, 3 },
                    { 1, 5 },
                    { 2, 4 },
                    { 2, 5 },
                    { 3, 1 },
                    { 3, 2 },
                    { 4, 1 },
                    { 4, 2 },
                    { 4, 5 },
                    { 5, 5 },
                    { 6, 3 },
                    { 6, 5 },
                    { 7, 2 },
                    { 7, 4 },
                    { 8, 4 },
                    { 8, 5 },
                    { 9, 2 },
                    { 9, 4 },
                    { 10, 4 },
                    { 11, 1 },
                    { 11, 5 },
                    { 12, 1 },
                    { 12, 4 },
                    { 13, 1 },
                    { 13, 3 },
                    { 13, 5 },
                    { 14, 2 },
                    { 14, 3 },
                    { 15, 3 },
                    { 15, 4 },
                    { 15, 5 },
                    { 16, 1 },
                    { 16, 3 },
                    { 17, 4 },
                    { 18, 1 },
                    { 18, 3 },
                    { 19, 3 },
                    { 20, 3 },
                    { 21, 4 },
                    { 22, 2 },
                    { 23, 1 },
                    { 24, 5 },
                    { 25, 2 },
                    { 25, 3 },
                    { 26, 3 },
                    { 27, 4 },
                    { 28, 2 },
                    { 29, 1 },
                    { 29, 4 },
                    { 30, 3 },
                    { 31, 3 },
                    { 32, 1 },
                    { 32, 2 },
                    { 33, 3 },
                    { 34, 1 },
                    { 34, 3 },
                    { 35, 4 },
                    { 36, 4 },
                    { 37, 4 },
                    { 37, 5 },
                    { 38, 2 },
                    { 38, 4 },
                    { 39, 3 },
                    { 39, 4 },
                    { 40, 1 },
                    { 40, 4 },
                    { 40, 5 },
                    { 41, 1 },
                    { 41, 2 },
                    { 41, 3 },
                    { 42, 2 },
                    { 42, 3 },
                    { 42, 4 },
                    { 43, 2 },
                    { 43, 5 },
                    { 44, 4 },
                    { 44, 5 },
                    { 45, 1 },
                    { 46, 2 },
                    { 46, 3 },
                    { 47, 2 },
                    { 48, 2 },
                    { 48, 5 },
                    { 49, 2 },
                    { 49, 4 },
                    { 50, 1 },
                    { 50, 4 },
                    { 51, 1 },
                    { 51, 4 },
                    { 52, 5 },
                    { 53, 2 },
                    { 53, 3 },
                    { 54, 1 },
                    { 54, 2 },
                    { 55, 2 },
                    { 56, 4 },
                    { 57, 3 },
                    { 57, 5 },
                    { 58, 3 },
                    { 58, 4 },
                    { 59, 3 },
                    { 60, 3 },
                    { 61, 4 },
                    { 61, 5 },
                    { 62, 4 },
                    { 62, 5 },
                    { 63, 2 },
                    { 63, 4 },
                    { 64, 1 },
                    { 64, 2 },
                    { 64, 3 },
                    { 65, 3 },
                    { 66, 3 },
                    { 67, 4 },
                    { 68, 1 },
                    { 68, 3 },
                    { 69, 2 },
                    { 69, 5 },
                    { 70, 2 },
                    { 70, 3 },
                    { 71, 1 },
                    { 71, 3 },
                    { 71, 5 },
                    { 72, 2 },
                    { 72, 4 },
                    { 73, 5 },
                    { 74, 5 },
                    { 75, 2 },
                    { 75, 4 },
                    { 76, 4 },
                    { 77, 3 },
                    { 78, 2 },
                    { 78, 3 },
                    { 79, 2 },
                    { 79, 4 },
                    { 80, 1 },
                    { 81, 4 },
                    { 81, 5 },
                    { 82, 1 },
                    { 82, 3 },
                    { 82, 4 },
                    { 83, 3 },
                    { 83, 4 },
                    { 84, 2 },
                    { 84, 4 },
                    { 84, 5 },
                    { 85, 3 },
                    { 85, 4 },
                    { 86, 3 },
                    { 87, 1 },
                    { 87, 5 },
                    { 88, 2 },
                    { 88, 3 },
                    { 89, 2 },
                    { 89, 5 },
                    { 90, 4 },
                    { 90, 5 },
                    { 91, 1 },
                    { 91, 3 },
                    { 91, 4 },
                    { 92, 2 },
                    { 92, 4 },
                    { 92, 5 },
                    { 93, 4 },
                    { 94, 1 },
                    { 94, 5 },
                    { 95, 1 },
                    { 95, 3 },
                    { 96, 3 },
                    { 96, 5 },
                    { 97, 3 },
                    { 97, 5 },
                    { 98, 1 },
                    { 98, 4 },
                    { 98, 5 },
                    { 99, 5 },
                    { 100, 2 }
                });

            migrationBuilder.InsertData(
                table: "buecher",
                columns: new[] { "BuchId", "AutorId", "Titel" },
                values: new object[,]
                {
                    { 1, 18, "laboris Riegelwood" },
                    { 2, 37, "exercitation Ilchester" },
                    { 3, 11, "culpa Bethany" },
                    { 4, 24, "minim Marenisco" },
                    { 5, 25, "fugiat Ticonderoga" },
                    { 6, 11, "eiusmod Morriston" },
                    { 7, 46, "eiusmod Joppa" },
                    { 8, 86, "tempor Sanborn" },
                    { 9, 87, "aute Lavalette" },
                    { 10, 12, "irure Wheaton" },
                    { 11, 34, "reprehenderit Dorneyville" },
                    { 12, 93, "labore Finzel" },
                    { 13, 24, "quis Woodburn" },
                    { 14, 85, "mollit Odessa" },
                    { 15, 100, "aute Cumberland" },
                    { 16, 19, "proident Homeworth" },
                    { 17, 73, "culpa Detroit" },
                    { 18, 10, "sunt Axis" },
                    { 19, 71, "ipsum Muir" },
                    { 20, 17, "ex Harborton" },
                    { 21, 65, "ex Outlook" },
                    { 22, 58, "consectetur Vincent" },
                    { 23, 94, "laboris Caspar" },
                    { 24, 90, "voluptate Harold" },
                    { 25, 10, "aliqua Whitehaven" },
                    { 26, 66, "pariatur Madrid" },
                    { 27, 80, "esse Needmore" },
                    { 28, 6, "tempor Cecilia" },
                    { 29, 68, "excepteur Charco" },
                    { 30, 57, "excepteur Brady" },
                    { 31, 26, "non Snyderville" },
                    { 32, 62, "commodo Seymour" },
                    { 33, 86, "occaecat Caroleen" },
                    { 34, 65, "nisi Croom" },
                    { 35, 3, "aliquip Gibsonia" },
                    { 36, 21, "cillum Clay" },
                    { 37, 41, "pariatur Yardville" },
                    { 38, 49, "tempor Smock" },
                    { 39, 22, "tempor Bentonville" },
                    { 40, 43, "excepteur Springdale" },
                    { 41, 13, "aliquip Elliston" },
                    { 42, 47, "sunt Linwood" },
                    { 43, 73, "quis Worcester" },
                    { 44, 90, "irure Torboy" },
                    { 45, 41, "reprehenderit Hayden" },
                    { 46, 17, "sunt Buxton" },
                    { 47, 97, "esse Sussex" },
                    { 48, 100, "id Harviell" },
                    { 49, 97, "dolore Maplewood" },
                    { 50, 44, "eu Kilbourne" },
                    { 51, 25, "ut Manchester" },
                    { 52, 3, "voluptate Riner" },
                    { 53, 28, "aliqua Rivereno" },
                    { 54, 30, "aliqua Westwood" },
                    { 55, 77, "excepteur Taft" },
                    { 56, 30, "minim Accoville" },
                    { 57, 11, "fugiat Kenvil" },
                    { 58, 12, "ut Watrous" },
                    { 59, 38, "pariatur Deltaville" },
                    { 60, 100, "occaecat Dale" },
                    { 61, 14, "amet Brownsville" },
                    { 62, 60, "cillum Fivepointville" },
                    { 63, 92, "commodo Tyhee" },
                    { 64, 1, "est Ellerslie" },
                    { 65, 28, "sint Sperryville" },
                    { 66, 100, "duis Nutrioso" },
                    { 67, 10, "laborum Clarksburg" },
                    { 68, 16, "Lorem Deseret" },
                    { 69, 86, "in Gracey" },
                    { 70, 58, "anim Wiscon" },
                    { 71, 58, "voluptate Garberville" },
                    { 72, 6, "Lorem Kent" },
                    { 73, 94, "veniam Curtice" },
                    { 74, 76, "amet Brooktrails" },
                    { 75, 9, "veniam Emison" },
                    { 76, 97, "ipsum Glenbrook" },
                    { 77, 15, "ut Basye" },
                    { 78, 51, "exercitation Stewartville" },
                    { 79, 27, "culpa Soham" },
                    { 80, 25, "est Kempton" },
                    { 81, 31, "ea Shepardsville" },
                    { 82, 47, "veniam Brecon" },
                    { 83, 23, "et Wildwood" },
                    { 84, 32, "sint Chamizal" },
                    { 85, 72, "fugiat Knowlton" },
                    { 86, 3, "qui Temperanceville" },
                    { 87, 33, "aliqua Williston" },
                    { 88, 52, "excepteur Bison" },
                    { 89, 18, "ea Bendon" },
                    { 90, 25, "elit Orin" },
                    { 91, 34, "dolore Jacksonburg" },
                    { 92, 50, "enim Keller" },
                    { 93, 3, "consequat Vale" },
                    { 94, 65, "irure Ryderwood" },
                    { 95, 20, "fugiat Masthope" },
                    { 96, 29, "labore Richville" },
                    { 97, 27, "consequat Mooresburg" },
                    { 98, 27, "tempor Waterview" },
                    { 99, 92, "aliquip Elbert" },
                    { 100, 82, "dolor Shrewsbury" },
                    { 101, 71, "labore Englevale" },
                    { 102, 87, "sunt Libertytown" },
                    { 103, 23, "non Vowinckel" },
                    { 104, 32, "esse Boling" },
                    { 105, 4, "velit Rosedale" },
                    { 106, 59, "nisi Greenock" },
                    { 107, 93, "nostrud Catharine" },
                    { 108, 90, "pariatur Zarephath" },
                    { 109, 67, "voluptate Fidelis" },
                    { 110, 29, "tempor Robinson" },
                    { 111, 63, "laboris Dana" },
                    { 112, 35, "nisi Ventress" },
                    { 113, 81, "dolor Belfair" },
                    { 114, 95, "nulla Woodlands" },
                    { 115, 31, "esse Loomis" },
                    { 116, 32, "ullamco Vicksburg" },
                    { 117, 15, "sunt Snowville" },
                    { 118, 61, "velit Rote" },
                    { 119, 98, "ipsum Nanafalia" },
                    { 120, 48, "minim Lund" },
                    { 121, 28, "mollit Villarreal" },
                    { 122, 48, "cillum Marienthal" },
                    { 123, 10, "voluptate Canoochee" },
                    { 124, 87, "dolore Waumandee" },
                    { 125, 31, "sit Winesburg" },
                    { 126, 92, "fugiat Navarre" },
                    { 127, 86, "sit Oceola" },
                    { 128, 68, "anim Jardine" },
                    { 129, 20, "consequat Glidden" },
                    { 130, 79, "qui Smeltertown" },
                    { 131, 97, "dolore Selma" },
                    { 132, 82, "est Jacumba" },
                    { 133, 51, "nostrud Helen" },
                    { 134, 30, "aliquip Savannah" },
                    { 135, 76, "cillum Somerset" },
                    { 136, 49, "velit Walland" },
                    { 137, 72, "deserunt Moscow" },
                    { 138, 32, "nisi Windsor" },
                    { 139, 59, "est Rosine" },
                    { 140, 92, "sunt Gulf" },
                    { 141, 63, "Lorem Stockwell" },
                    { 142, 46, "qui Hoehne" },
                    { 143, 43, "dolore Collins" },
                    { 144, 13, "quis Moquino" },
                    { 145, 82, "laboris Fairhaven" },
                    { 146, 98, "proident Allentown" },
                    { 147, 80, "velit Baker" },
                    { 148, 85, "proident Crumpler" },
                    { 149, 15, "ea Lydia" },
                    { 150, 53, "sit Thermal" },
                    { 151, 54, "ex Springville" },
                    { 152, 96, "esse Cornucopia" },
                    { 153, 71, "qui Hartsville/Hartley" },
                    { 154, 47, "ullamco Joes" },
                    { 155, 83, "ad Taycheedah" },
                    { 156, 69, "laboris Kaka" },
                    { 157, 49, "minim Lorraine" },
                    { 158, 78, "nostrud Cliff" },
                    { 159, 29, "aute Wattsville" },
                    { 160, 32, "do Sanford" },
                    { 161, 79, "est Bowden" },
                    { 162, 54, "aliqua Cuylerville" },
                    { 163, 58, "ad Chloride" },
                    { 164, 49, "duis Bladensburg" },
                    { 165, 69, "sint Whipholt" },
                    { 166, 35, "nostrud Juarez" },
                    { 167, 80, "officia Frizzleburg" },
                    { 168, 91, "ea Verdi" },
                    { 169, 15, "officia Bend" },
                    { 170, 68, "voluptate Ernstville" },
                    { 171, 12, "proident Columbus" },
                    { 172, 34, "sunt Bradenville" },
                    { 173, 73, "sint Why" },
                    { 174, 78, "irure Dexter" },
                    { 175, 52, "dolore Dante" },
                    { 176, 17, "anim Martinsville" },
                    { 177, 66, "ullamco Retsof" },
                    { 178, 55, "velit Heil" },
                    { 179, 50, "cupidatat Cartwright" },
                    { 180, 53, "reprehenderit Klagetoh" },
                    { 181, 72, "proident Osmond" },
                    { 182, 50, "adipisicing Movico" },
                    { 183, 55, "in Waiohinu" },
                    { 184, 33, "elit Alamo" },
                    { 185, 57, "culpa Iola" },
                    { 186, 80, "exercitation Bluffview" },
                    { 187, 73, "pariatur Gadsden" },
                    { 188, 16, "laborum Martell" },
                    { 189, 57, "aute Defiance" },
                    { 190, 69, "eu Gouglersville" },
                    { 191, 80, "eiusmod Salunga" },
                    { 192, 47, "adipisicing Hiwasse" },
                    { 193, 24, "labore Carlos" },
                    { 194, 75, "tempor Richmond" },
                    { 195, 22, "culpa Romeville" },
                    { 196, 29, "nostrud Brethren" },
                    { 197, 2, "exercitation Turpin" },
                    { 198, 64, "in Edgewater" },
                    { 199, 68, "aliquip Cedarville" },
                    { 200, 74, "voluptate Southmont" },
                    { 201, 52, "duis Stockdale" },
                    { 202, 61, "aliquip Brownlee" },
                    { 203, 66, "ullamco Independence" },
                    { 204, 29, "consequat Mapletown" },
                    { 205, 93, "in Dubois" },
                    { 206, 3, "tempor Idamay" },
                    { 207, 86, "commodo Turah" },
                    { 208, 1, "reprehenderit Umapine" },
                    { 209, 27, "officia Bartley" },
                    { 210, 99, "tempor Hiko" },
                    { 211, 21, "incididunt Wanship" },
                    { 212, 81, "labore Gambrills" },
                    { 213, 42, "culpa Sattley" },
                    { 214, 92, "aliquip Cornfields" },
                    { 215, 55, "aute Belva" },
                    { 216, 26, "laboris Mayfair" },
                    { 217, 88, "pariatur Robbins" },
                    { 218, 19, "magna Emory" },
                    { 219, 87, "quis Juntura" },
                    { 220, 96, "cillum Stouchsburg" },
                    { 221, 87, "consequat Austinburg" },
                    { 222, 91, "eu Hailesboro" },
                    { 223, 40, "nisi Gardiner" },
                    { 224, 52, "ea Bluetown" },
                    { 225, 49, "do Nipinnawasee" },
                    { 226, 98, "velit Abiquiu" },
                    { 227, 91, "anim Sedley" },
                    { 228, 81, "nisi Zeba" },
                    { 229, 38, "minim Lindisfarne" },
                    { 230, 50, "adipisicing Lookingglass" },
                    { 231, 80, "ut Kylertown" },
                    { 232, 70, "officia Sutton" },
                    { 233, 45, "qui Ezel" },
                    { 234, 21, "non Coleville" },
                    { 235, 25, "deserunt Virgie" },
                    { 236, 38, "culpa Crenshaw" },
                    { 237, 53, "adipisicing Hendersonville" },
                    { 238, 61, "aliqua Matthews" },
                    { 239, 1, "deserunt Foscoe" },
                    { 240, 93, "in Saranap" },
                    { 241, 58, "nisi Vandiver" },
                    { 242, 57, "veniam Wadsworth" },
                    { 243, 57, "commodo Chicopee" },
                    { 244, 35, "qui Morgandale" },
                    { 245, 60, "consequat Haena" },
                    { 246, 4, "do Barrelville" },
                    { 247, 20, "magna Yorklyn" },
                    { 248, 97, "consequat Tetherow" },
                    { 249, 50, "nulla Whitewater" },
                    { 250, 68, "adipisicing Hannasville" },
                    { 251, 22, "laboris Makena" },
                    { 252, 32, "adipisicing Limestone" },
                    { 253, 24, "ipsum Bennett" },
                    { 254, 97, "incididunt Indio" },
                    { 255, 96, "ea Kapowsin" },
                    { 256, 4, "tempor Drytown" },
                    { 257, 73, "proident Robinette" },
                    { 258, 1, "fugiat Chemung" },
                    { 259, 93, "magna Greensburg" },
                    { 260, 42, "reprehenderit Roosevelt" },
                    { 261, 38, "mollit Boomer" },
                    { 262, 73, "ad Thatcher" },
                    { 263, 67, "nulla Fairmount" },
                    { 264, 88, "eiusmod Sena" },
                    { 265, 56, "amet Watchtower" },
                    { 266, 39, "aute Rodanthe" },
                    { 267, 45, "nulla Orick" },
                    { 268, 93, "pariatur Hasty" },
                    { 269, 10, "labore Crawfordsville" },
                    { 270, 30, "incididunt Mathews" },
                    { 271, 95, "nostrud Kansas" },
                    { 272, 20, "est Cucumber" },
                    { 273, 74, "labore Highland" },
                    { 274, 83, "id Singer" },
                    { 275, 37, "laborum Tilden" },
                    { 276, 65, "aliquip Guthrie" },
                    { 277, 39, "ipsum Idledale" },
                    { 278, 79, "deserunt Utting" },
                    { 279, 34, "est Salix" },
                    { 280, 73, "qui Campo" },
                    { 281, 100, "ad Oley" },
                    { 282, 62, "ullamco Brule" },
                    { 283, 4, "eiusmod Bridgetown" },
                    { 284, 22, "ullamco Northridge" },
                    { 285, 4, "ea Allamuchy" },
                    { 286, 56, "deserunt Mappsville" },
                    { 287, 82, "et Dyckesville" },
                    { 288, 61, "tempor Sabillasville" },
                    { 289, 7, "ullamco Carbonville" },
                    { 290, 35, "quis Glenville" },
                    { 291, 56, "cupidatat Bonanza" },
                    { 292, 77, "culpa Hiseville" },
                    { 293, 53, "dolore Barstow" },
                    { 294, 67, "eiusmod Delco" },
                    { 295, 66, "consequat Calverton" },
                    { 296, 10, "cupidatat Babb" },
                    { 297, 48, "amet Gerton" },
                    { 298, 99, "non Hatteras" },
                    { 299, 27, "esse Goodville" },
                    { 300, 78, "velit Trexlertown" },
                    { 301, 22, "laboris Enlow" },
                    { 302, 29, "ipsum Gasquet" },
                    { 303, 90, "nostrud Caron" },
                    { 304, 62, "proident Denio" },
                    { 305, 75, "amet Cressey" },
                    { 306, 79, "eu Tolu" },
                    { 307, 86, "ullamco Leyner" },
                    { 308, 12, "nulla Montura" },
                    { 309, 11, "do Lindcove" },
                    { 310, 79, "in Lawrence" },
                    { 311, 65, "laboris Bellfountain" },
                    { 312, 72, "nisi Swartzville" },
                    { 313, 78, "consequat Rossmore" },
                    { 314, 76, "quis Crisman" },
                    { 315, 95, "eu Leola" },
                    { 316, 9, "dolore Lemoyne" },
                    { 317, 50, "consectetur Statenville" },
                    { 318, 62, "ipsum Oneida" },
                    { 319, 48, "ex Woodlake" },
                    { 320, 20, "ullamco Fowlerville" },
                    { 321, 10, "irure Fairlee" },
                    { 322, 39, "labore Datil" },
                    { 323, 94, "eu Edmund" },
                    { 324, 92, "do Ahwahnee" },
                    { 325, 11, "magna Westmoreland" },
                    { 326, 17, "anim Cleary" },
                    { 327, 32, "laboris Lafferty" },
                    { 328, 57, "deserunt Santel" },
                    { 329, 39, "in Succasunna" },
                    { 330, 89, "nulla Leland" },
                    { 331, 33, "ut Florence" },
                    { 332, 98, "ullamco Frystown" },
                    { 333, 99, "proident Ada" },
                    { 334, 91, "ea Blairstown" },
                    { 335, 93, "minim Norwood" },
                    { 336, 1, "sunt Grenelefe" },
                    { 337, 31, "quis Vallonia" },
                    { 338, 49, "sunt Eagleville" },
                    { 339, 37, "culpa Clarence" },
                    { 340, 88, "Lorem Eden" },
                    { 341, 20, "mollit Sparkill" },
                    { 342, 11, "elit Blandburg" },
                    { 343, 93, "anim Farmers" },
                    { 344, 16, "esse Blue" },
                    { 345, 62, "pariatur Deercroft" },
                    { 346, 71, "laborum Leroy" },
                    { 347, 14, "pariatur Inkerman" },
                    { 348, 80, "incididunt Bodega" },
                    { 349, 20, "Lorem Dowling" },
                    { 350, 82, "sunt Deputy" },
                    { 351, 89, "minim Takilma" },
                    { 352, 58, "et Islandia" },
                    { 353, 21, "aliquip Shasta" },
                    { 354, 65, "anim Townsend" },
                    { 355, 79, "eu Bordelonville" },
                    { 356, 16, "in Coinjock" },
                    { 357, 75, "consequat Cashtown" },
                    { 358, 92, "in Boykin" },
                    { 359, 28, "sint Blanco" },
                    { 360, 8, "fugiat Forbestown" },
                    { 361, 28, "ex Ironton" },
                    { 362, 100, "proident Bagtown" },
                    { 363, 92, "velit Sehili" },
                    { 364, 31, "nulla Macdona" },
                    { 365, 69, "minim Coral" },
                    { 366, 79, "reprehenderit Cawood" },
                    { 367, 67, "sunt Connerton" },
                    { 368, 49, "velit Grandview" },
                    { 369, 44, "minim Manitou" },
                    { 370, 59, "esse Loma" },
                    { 371, 43, "quis Strong" },
                    { 372, 69, "irure Veguita" },
                    { 373, 88, "exercitation Hall" },
                    { 374, 49, "consequat Derwood" },
                    { 375, 50, "ut Gorham" },
                    { 376, 32, "nulla Konterra" },
                    { 377, 11, "aliquip Kohatk" },
                    { 378, 97, "sint Rose" },
                    { 379, 53, "fugiat Jennings" },
                    { 380, 70, "voluptate Ypsilanti" },
                    { 381, 63, "magna Noxen" },
                    { 382, 48, "consequat Graball" },
                    { 383, 46, "do Thomasville" },
                    { 384, 75, "labore Clara" },
                    { 385, 1, "labore Veyo" },
                    { 386, 38, "cupidatat Gila" },
                    { 387, 51, "occaecat Hollins" },
                    { 388, 28, "duis Bedias" },
                    { 389, 46, "quis Concho" },
                    { 390, 93, "incididunt Foxworth" },
                    { 391, 13, "magna Yukon" },
                    { 392, 89, "velit Sexton" },
                    { 393, 83, "proident Roy" },
                    { 394, 83, "aliquip Nogal" },
                    { 395, 97, "deserunt Chase" },
                    { 396, 74, "adipisicing Templeton" },
                    { 397, 90, "eu Rodman" },
                    { 398, 89, "fugiat Newry" },
                    { 399, 4, "labore Gerber" },
                    { 400, 71, "labore Wright" },
                    { 401, 59, "aliquip Newcastle" },
                    { 402, 81, "qui Topaz" },
                    { 403, 18, "in Witmer" },
                    { 404, 82, "labore Staples" },
                    { 405, 22, "consectetur Savage" },
                    { 406, 19, "aliquip Bourg" },
                    { 407, 9, "elit Courtland" },
                    { 408, 61, "elit Imperial" },
                    { 409, 48, "pariatur Woodruff" },
                    { 410, 96, "incididunt Ballico" },
                    { 411, 84, "minim Herbster" },
                    { 412, 45, "nisi Dodge" },
                    { 413, 5, "voluptate Summertown" },
                    { 414, 11, "adipisicing Baden" },
                    { 415, 70, "enim Homestead" },
                    { 416, 91, "sit Teasdale" },
                    { 417, 49, "est Jugtown" },
                    { 418, 18, "exercitation Rutherford" },
                    { 419, 74, "reprehenderit Glendale" },
                    { 420, 11, "est Orviston" },
                    { 421, 12, "ullamco Olney" },
                    { 422, 88, "fugiat Chelsea" },
                    { 423, 19, "tempor Tuskahoma" },
                    { 424, 12, "ea Fruitdale" },
                    { 425, 35, "laboris Wolcott" },
                    { 426, 88, "voluptate Craig" },
                    { 427, 100, "qui Ogema" },
                    { 428, 65, "ea Magnolia" },
                    { 429, 83, "esse Guilford" },
                    { 430, 87, "culpa Venice" },
                    { 431, 68, "duis Gibbsville" },
                    { 432, 30, "nostrud Adelino" },
                    { 433, 37, "quis Kipp" },
                    { 434, 5, "enim Websterville" },
                    { 435, 50, "veniam Cataract" },
                    { 436, 29, "reprehenderit Gwynn" },
                    { 437, 68, "cupidatat Advance" },
                    { 438, 78, "est Noblestown" },
                    { 439, 40, "culpa Cochranville" },
                    { 440, 56, "veniam Richford" },
                    { 441, 28, "Lorem Colton" },
                    { 442, 44, "et Hampstead" },
                    { 443, 53, "incididunt Steinhatchee" },
                    { 444, 83, "quis Lisco" },
                    { 445, 75, "et Roberts" },
                    { 446, 96, "eu Waukeenah" },
                    { 447, 59, "officia Alafaya" },
                    { 448, 31, "laboris Bowie" },
                    { 449, 54, "ut Roderfield" },
                    { 450, 15, "qui Urbana" },
                    { 451, 53, "enim Boyd" },
                    { 452, 22, "sunt Draper" },
                    { 453, 27, "proident Fredericktown" },
                    { 454, 17, "nostrud Hemlock" },
                    { 455, 23, "irure Dahlen" },
                    { 456, 73, "exercitation Hobucken" },
                    { 457, 77, "dolore Belgreen" },
                    { 458, 40, "laborum Driftwood" },
                    { 459, 75, "ipsum Carlton" },
                    { 460, 34, "ullamco Hamilton" },
                    { 461, 85, "ut Cresaptown" },
                    { 462, 94, "fugiat Cumminsville" },
                    { 463, 23, "esse Greenbackville" },
                    { 464, 96, "ullamco Morningside" },
                    { 465, 28, "fugiat Wauhillau" },
                    { 466, 62, "ea Avalon" },
                    { 467, 36, "eu Dupuyer" },
                    { 468, 26, "incididunt Hackneyville" },
                    { 469, 21, "laborum Bartonsville" },
                    { 470, 56, "ad Garfield" },
                    { 471, 35, "irure Waterford" },
                    { 472, 3, "nisi Darbydale" },
                    { 473, 84, "excepteur Hondah" },
                    { 474, 94, "pariatur Benson" },
                    { 475, 43, "consectetur Spelter" },
                    { 476, 77, "amet Waverly" },
                    { 477, 58, "adipisicing Cavalero" },
                    { 478, 33, "pariatur Blodgett" },
                    { 479, 72, "sit Fostoria" },
                    { 480, 63, "qui Jeff" },
                    { 481, 76, "anim Calpine" },
                    { 482, 3, "ex Manila" },
                    { 483, 88, "culpa Sultana" },
                    { 484, 5, "tempor Edgar" },
                    { 485, 41, "nulla Fairacres" },
                    { 486, 34, "sit Sims" },
                    { 487, 1, "eu Sylvanite" },
                    { 488, 71, "ut Matheny" },
                    { 489, 37, "anim Bangor" },
                    { 490, 59, "adipisicing Greenbush" },
                    { 491, 5, "sunt Flintville" },
                    { 492, 20, "ex Shelby" },
                    { 493, 83, "magna Chalfant" },
                    { 494, 43, "minim Sheatown" },
                    { 495, 28, "do Sugartown" },
                    { 496, 22, "duis Falconaire" },
                    { 497, 42, "eu Chaparrito" },
                    { 498, 54, "nisi Longbranch" },
                    { 499, 34, "adipisicing Condon" },
                    { 500, 2, "laboris Comptche" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_AutorBuecherei_BuechereiId",
                table: "AutorBuecherei",
                column: "BuechereiId");

            migrationBuilder.CreateIndex(
                name: "IX_buecher_AutorId",
                table: "buecher",
                column: "AutorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AutorBuecherei");

            migrationBuilder.DropTable(
                name: "buecher");

            migrationBuilder.DropTable(
                name: "buechereien");

            migrationBuilder.DropTable(
                name: "autoren");
        }
    }
}
